/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AuthActionRouteImport } from './routes/auth-action'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SearchRouteImport } from './routes/search'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as WatchlistRouteImport } from './routes/watchlist'
import { Route as MovieSlugRouteImport } from './routes/movie/$slug'
import { Route as MoviesIndexRouteImport } from './routes/movies/index'
import { Route as SeriesIndexRouteImport } from './routes/series/index'
import { Route as TvSlugRouteImport } from './routes/tv/$slug'
import { Route as MoviesGenreSlugIndexRouteImport } from './routes/movies/$genreSlug/index'
import { Route as MoviesGenreSlugSortSlugRouteImport } from './routes/movies/$genreSlug/$sortSlug'
import { Route as MoviesWatchSlugRouteImport } from './routes/movies/watch/$slug'
import { Route as PersonIdSlugRouteImport } from './routes/person/$id/$slug'
import { Route as SeriesGenreSlugIndexRouteImport } from './routes/series/$genreSlug/index'
import { Route as SeriesGenreSlugSortSlugRouteImport } from './routes/series/$genreSlug/$sortSlug'
import { Route as SeriesWatchSlugRouteImport } from './routes/series/watch/$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthActionRoute = AuthActionRouteImport.update({
  id: '/auth-action',
  path: '/auth-action',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const WatchlistRoute = WatchlistRouteImport.update({
  id: '/watchlist',
  path: '/watchlist',
  getParentRoute: () => rootRouteImport,
} as any)
const MovieSlugRoute = MovieSlugRouteImport.update({
  id: '/movie/$slug',
  path: '/movie/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const MoviesIndexRoute = MoviesIndexRouteImport.update({
  id: '/movies/',
  path: '/movies/',
  getParentRoute: () => rootRouteImport,
} as any)
const SeriesIndexRoute = SeriesIndexRouteImport.update({
  id: '/series/',
  path: '/series/',
  getParentRoute: () => rootRouteImport,
} as any)
const TvSlugRoute = TvSlugRouteImport.update({
  id: '/tv/$slug',
  path: '/tv/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const MoviesGenreSlugIndexRoute = MoviesGenreSlugIndexRouteImport.update({
  id: '/movies/$genreSlug/',
  path: '/movies/$genreSlug/',
  getParentRoute: () => rootRouteImport,
} as any)
const MoviesGenreSlugSortSlugRoute = MoviesGenreSlugSortSlugRouteImport.update({
  id: '/movies/$genreSlug/$sortSlug',
  path: '/movies/$genreSlug/$sortSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const MoviesWatchSlugRoute = MoviesWatchSlugRouteImport.update({
  id: '/movies/watch/$slug',
  path: '/movies/watch/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PersonIdSlugRoute = PersonIdSlugRouteImport.update({
  id: '/person/$id/$slug',
  path: '/person/$id/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const SeriesGenreSlugIndexRoute = SeriesGenreSlugIndexRouteImport.update({
  id: '/series/$genreSlug/',
  path: '/series/$genreSlug/',
  getParentRoute: () => rootRouteImport,
} as any)
const SeriesGenreSlugSortSlugRoute = SeriesGenreSlugSortSlugRouteImport.update({
  id: '/series/$genreSlug/$sortSlug',
  path: '/series/$genreSlug/$sortSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const SeriesWatchSlugRoute = SeriesWatchSlugRouteImport.update({
  id: '/series/watch/$slug',
  path: '/series/watch/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/auth-action': typeof AuthActionRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/verify-email': typeof VerifyEmailRoute
  '/watchlist': typeof WatchlistRoute
  '/movie/$slug': typeof MovieSlugRoute
  '/tv/$slug': typeof TvSlugRoute
  '/movies/': typeof MoviesIndexRoute
  '/series/': typeof SeriesIndexRoute
  '/movies/$genreSlug/$sortSlug': typeof MoviesGenreSlugSortSlugRoute
  '/movies/watch/$slug': typeof MoviesWatchSlugRoute
  '/person/$id/$slug': typeof PersonIdSlugRoute
  '/series/$genreSlug/$sortSlug': typeof SeriesGenreSlugSortSlugRoute
  '/series/watch/$slug': typeof SeriesWatchSlugRoute
  '/movies/$genreSlug/': typeof MoviesGenreSlugIndexRoute
  '/series/$genreSlug/': typeof SeriesGenreSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/auth-action': typeof AuthActionRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/verify-email': typeof VerifyEmailRoute
  '/watchlist': typeof WatchlistRoute
  '/movie/$slug': typeof MovieSlugRoute
  '/tv/$slug': typeof TvSlugRoute
  '/movies': typeof MoviesIndexRoute
  '/series': typeof SeriesIndexRoute
  '/movies/$genreSlug/$sortSlug': typeof MoviesGenreSlugSortSlugRoute
  '/movies/watch/$slug': typeof MoviesWatchSlugRoute
  '/person/$id/$slug': typeof PersonIdSlugRoute
  '/series/$genreSlug/$sortSlug': typeof SeriesGenreSlugSortSlugRoute
  '/series/watch/$slug': typeof SeriesWatchSlugRoute
  '/movies/$genreSlug': typeof MoviesGenreSlugIndexRoute
  '/series/$genreSlug': typeof SeriesGenreSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/auth-action': typeof AuthActionRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/verify-email': typeof VerifyEmailRoute
  '/watchlist': typeof WatchlistRoute
  '/movie/$slug': typeof MovieSlugRoute
  '/tv/$slug': typeof TvSlugRoute
  '/movies/': typeof MoviesIndexRoute
  '/series/': typeof SeriesIndexRoute
  '/movies/$genreSlug/$sortSlug': typeof MoviesGenreSlugSortSlugRoute
  '/movies/watch/$slug': typeof MoviesWatchSlugRoute
  '/person/$id/$slug': typeof PersonIdSlugRoute
  '/series/$genreSlug/$sortSlug': typeof SeriesGenreSlugSortSlugRoute
  '/series/watch/$slug': typeof SeriesWatchSlugRoute
  '/movies/$genreSlug/': typeof MoviesGenreSlugIndexRoute
  '/series/$genreSlug/': typeof SeriesGenreSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/auth-action'
    | '/reset-password'
    | '/search'
    | '/verify-email'
    | '/watchlist'
    | '/movie/$slug'
    | '/tv/$slug'
    | '/movies/'
    | '/series/'
    | '/movies/$genreSlug/$sortSlug'
    | '/movies/watch/$slug'
    | '/person/$id/$slug'
    | '/series/$genreSlug/$sortSlug'
    | '/series/watch/$slug'
    | '/movies/$genreSlug/'
    | '/series/$genreSlug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/auth-action'
    | '/reset-password'
    | '/search'
    | '/verify-email'
    | '/watchlist'
    | '/movie/$slug'
    | '/tv/$slug'
    | '/movies'
    | '/series'
    | '/movies/$genreSlug/$sortSlug'
    | '/movies/watch/$slug'
    | '/person/$id/$slug'
    | '/series/$genreSlug/$sortSlug'
    | '/series/watch/$slug'
    | '/movies/$genreSlug'
    | '/series/$genreSlug'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/auth-action'
    | '/reset-password'
    | '/search'
    | '/verify-email'
    | '/watchlist'
    | '/movie/$slug'
    | '/tv/$slug'
    | '/movies/'
    | '/series/'
    | '/movies/$genreSlug/$sortSlug'
    | '/movies/watch/$slug'
    | '/person/$id/$slug'
    | '/series/$genreSlug/$sortSlug'
    | '/series/watch/$slug'
    | '/movies/$genreSlug/'
    | '/series/$genreSlug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  AuthActionRoute: typeof AuthActionRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SearchRoute: typeof SearchRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  WatchlistRoute: typeof WatchlistRoute
  MovieSlugRoute: typeof MovieSlugRoute
  TvSlugRoute: typeof TvSlugRoute
  MoviesIndexRoute: typeof MoviesIndexRoute
  SeriesIndexRoute: typeof SeriesIndexRoute
  MoviesGenreSlugSortSlugRoute: typeof MoviesGenreSlugSortSlugRoute
  MoviesWatchSlugRoute: typeof MoviesWatchSlugRoute
  PersonIdSlugRoute: typeof PersonIdSlugRoute
  SeriesGenreSlugSortSlugRoute: typeof SeriesGenreSlugSortSlugRoute
  SeriesWatchSlugRoute: typeof SeriesWatchSlugRoute
  MoviesGenreSlugIndexRoute: typeof MoviesGenreSlugIndexRoute
  SeriesGenreSlugIndexRoute: typeof SeriesGenreSlugIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth-action': {
      id: '/auth-action'
      path: '/auth-action'
      fullPath: '/auth-action'
      preLoaderRoute: typeof AuthActionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watchlist': {
      id: '/watchlist'
      path: '/watchlist'
      fullPath: '/watchlist'
      preLoaderRoute: typeof WatchlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movie/$slug': {
      id: '/movie/$slug'
      path: '/movie/$slug'
      fullPath: '/movie/$slug'
      preLoaderRoute: typeof MovieSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movies/': {
      id: '/movies/'
      path: '/movies'
      fullPath: '/movies/'
      preLoaderRoute: typeof MoviesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/series/': {
      id: '/series/'
      path: '/series'
      fullPath: '/series/'
      preLoaderRoute: typeof SeriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tv/$slug': {
      id: '/tv/$slug'
      path: '/tv/$slug'
      fullPath: '/tv/$slug'
      preLoaderRoute: typeof TvSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movies/$genreSlug/': {
      id: '/movies/$genreSlug/'
      path: '/movies/$genreSlug'
      fullPath: '/movies/$genreSlug/'
      preLoaderRoute: typeof MoviesGenreSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movies/$genreSlug/$sortSlug': {
      id: '/movies/$genreSlug/$sortSlug'
      path: '/movies/$genreSlug/$sortSlug'
      fullPath: '/movies/$genreSlug/$sortSlug'
      preLoaderRoute: typeof MoviesGenreSlugSortSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movies/watch/$slug': {
      id: '/movies/watch/$slug'
      path: '/movies/watch/$slug'
      fullPath: '/movies/watch/$slug'
      preLoaderRoute: typeof MoviesWatchSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/person/$id/$slug': {
      id: '/person/$id/$slug'
      path: '/person/$id/$slug'
      fullPath: '/person/$id/$slug'
      preLoaderRoute: typeof PersonIdSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/series/$genreSlug/': {
      id: '/series/$genreSlug/'
      path: '/series/$genreSlug'
      fullPath: '/series/$genreSlug/'
      preLoaderRoute: typeof SeriesGenreSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/series/$genreSlug/$sortSlug': {
      id: '/series/$genreSlug/$sortSlug'
      path: '/series/$genreSlug/$sortSlug'
      fullPath: '/series/$genreSlug/$sortSlug'
      preLoaderRoute: typeof SeriesGenreSlugSortSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/series/watch/$slug': {
      id: '/series/watch/$slug'
      path: '/series/watch/$slug'
      fullPath: '/series/watch/$slug'
      preLoaderRoute: typeof SeriesWatchSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  AuthActionRoute: AuthActionRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SearchRoute: SearchRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  WatchlistRoute: WatchlistRoute,
  MovieSlugRoute: MovieSlugRoute,
  TvSlugRoute: TvSlugRoute,
  MoviesIndexRoute: MoviesIndexRoute,
  SeriesIndexRoute: SeriesIndexRoute,
  MoviesGenreSlugSortSlugRoute: MoviesGenreSlugSortSlugRoute,
  MoviesWatchSlugRoute: MoviesWatchSlugRoute,
  PersonIdSlugRoute: PersonIdSlugRoute,
  SeriesGenreSlugSortSlugRoute: SeriesGenreSlugSortSlugRoute,
  SeriesWatchSlugRoute: SeriesWatchSlugRoute,
  MoviesGenreSlugIndexRoute: MoviesGenreSlugIndexRoute,
  SeriesGenreSlugIndexRoute: SeriesGenreSlugIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
